version: "2"

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused

issues:
  exclude-rules:
    - path: internal/repository/generated/
      linters:
        - errcheck
        - unused
        - staticcheck
        - govet
        - gofmt
